update generator
easysoftware/rys pull request #19
Opened 2019-04-12 09:44 UTC by luk4s

* remove useless rubocop.yml (because this dont respect all others code)
* add simplecov to generated rys for more accuracy

2019-04-17 09:19 UTC, ondra-m commented
Did you test it? :)

2019-07-17 18:34 UTC, luk4s commented
Current version - rubocop raise error:
```
Error:Rubocop returned exit code: 2
stderr:
Error: obsolete `EnforcedStyle: rails` (for Layout/IndentationConsistency) found in .rubocop.yml
`EnforcedStyle: rails` has been renamed to `EnforcedStyle: indented_internal_methods`
```

+ improve spec_helper.rb.tt 😉

2019-07-19 05:23 UTC, ondra-m requested changes

2019-07-19 05:23 UTC, ondra-m commented on lib/generators/rys/plugin/templates/spec/spec_helper.rb.tt
> +  add_filter 'lib/<%= name %>/version'
Can you do this in ryspec?
Iterate over all plugins and add filter?

2019-07-19 09:37 UTC, closed without merging