Disabled ES#326019
easysoftware/rys pull request #28
Opened 2020-02-08 21:10 UTC by ahorek

draft...

2020-02-10 15:10 UTC, ondra-m requested changes

2020-02-10 15:10 UTC, ondra-m commented on lib/rys/engine_extensions.rb
> +      def active?
Engine is always active. The name doesn't make sense

2020-02-10 15:10 UTC, ondra-m commented on app/models/rys_feature_record.rb
> +    record&.active? && hosting_active?(record&.feature&.plugins&.first)
why just `.first`?

2020-02-10 15:10 UTC, ondra-m commented on app/models/rys_feature_record.rb
> +  def self.hosting_active?(plugin)
I don't like this solution. If you have plugin `pavel` with features `pavel.**.*` -> easy_hosting_service can just set

```ruby
Rys::Feature.add("pavel") do
  false
end

2020-02-14 05:53 UTC, ondra-m requested changes

2020-02-14 05:53 UTC, ondra-m commented on lib/rys/engine_extensions.rb
> +      def plugin_active?
Stejně jako v managementu

tady může být

```ruby
def plugin_active?
   true
end
```
a hosting service to patchne

2020-02-14 05:53 UTC, ondra-m commented on lib/rys/engine_extensions.rb
> +      def plugin_id(name=nil)
Jaký je rozdíl v `rys_id`?

2020-02-14 16:35 UTC, ahorek commented on lib/rys/engine_extensions.rb
> +      def plugin_id(name=nil)
název rys pluginu může být jiný jak název rysu

2020-02-14 19:01 UTC, ahorek commented on lib/rys/engine_extensions.rb
> +      def plugin_id(name=nil)
upraveno na rys_id

2020-02-19 08:52 UTC, luk4s requested changes

2020-02-19 08:52 UTC, luk4s commented on lib/rys/engine_extensions.rb
> +      def deactivated_plugin_html(_view_context)
Prosím k čemu je tato metoda? Bylo by možné přidat komentář který by vysvětloval její použití? Za rok nikdo nebude vědět na co to je... 
díky

2020-02-19 13:58 UTC, luk4s approved these changes

2020-02-24 11:40 UTC, merged